import Head from "next/head";
import Feed from "../components/Feed/Feed";

import Sidebar from "../components/Sidebar/Sidebar";
import Widgets from "../components/Widgets/Widgets";

export default function Home({ newsResults, userResults }) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
        {/* SIDEBAR */}
        <Sidebar />

        {/* FEED */}
        <Feed />

        {/* WIDGETS */}
        <Widgets
          newsResults={newsResults.articles}
          userResults={userResults.results}
        />

        {/* MODAL */}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // News section
  const newsUrl =
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json";
  const newsResults = await fetch(newsUrl)
    .then((res) => res.json())
    .catch((error) => console.log(error));

  //Who to follow section
  const userResults = await fetch(
    "https://randomuser.me/api/?results=40&inc=name,login,picture"
  )
    .then((res) => res.json())
    .catch((error) => console.log(error));

  return {
    props: { newsResults, userResults },
  };
}
