import Head from "next/head";

import Sidebar from "../components/Sidebar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto max-w-[1600px] ">
        {/* SIDEBAR */}
        <Sidebar />

        {/* FEED */}

        {/* WIDGETS */}

        {/* MODAL */}
      </main>
    </>
  );
}
